name: C++

on:
  push:
    paths:
      - '**.cpp'

jobs:
  auto-format:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Install clang-format@16 and Poac
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install clang-format@16 poac
          echo '/home/linuxbrew/.linuxbrew/opt/clang-format/bin' >> $GITHUB_PATH

      - name: Format code
        run: |
          poac init
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          poac --verbose fmt

      - name: Remove Poac Manifest File
        run: rm poac.toml

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v4
