name: Rust

on:
  push:
    paths:
      - '**.rs'

jobs:
  auto-format:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Format code
        run: rustfmt **/*.rs

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v4
